import type { Metadata } from 'next'
import localFont from 'next/font/local'
import classNames from 'classnames/bind'

import { Providers } from '@/app/providers'
import Header from '@/components/common/Header/Header'
import Footer from '@/components/common/Footer/Footer'

import '@/styles/base/common.scss'
import styles from './layout.module.scss'

const cx = classNames.bind(styles)

export const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2'
})

export const metadata: Metadata = {
  title: 'Quick Question',
  description: 'Generated by create next app'
}

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={pretendard.className}>
        <Providers>
          <Header />
          <div className={cx('container')}>
            <main className={cx('main')}>{children}</main>
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout
